# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SwallowTales', '0004_auto_20160306_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storysection',
            name='previousSection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='SwallowTales.StorySection'),
        ),
    ]
