# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SwallowTales', '0005_auto_20160306_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storysection',
            old_name='name',
            new_name='secName',
        ),
    ]
