# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwallowTales', '0006_auto_20160306_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='LastDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
