# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StorySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='storysection',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SwallowTales.User'),
        ),
        migrations.AddField(
            model_name='storysection',
            name='previousSection',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='SwallowTales.StorySection'),
        ),
        migrations.AddField(
            model_name='storysection',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SwallowTales.Story'),
        ),
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SwallowTales.User'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SwallowTales.StorySection'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SwallowTales.User'),
        ),
    ]
